### ISSUE TITLE
JSON parse throws error

### ISSUE THREAD

**Issue by legetz** [claudiajs/claudia-api-builder#30]
When calling claudia API using HTTP POST and invalid JSON like:
{test:true}

One will get following error:
{
  "message": "Internal server error"
}

=>

SyntaxError: Unexpected token t
    at Object.parse (native)
    at convertApiGWProxyRequest (/var/task/node_modules/claudia-api-builder/src/convert-api-gw-proxy-request.js:80:22)
    at ApiBuilder.getRequest (/var/task/node_modules/claudia-api-builder/src/api-builder.js:233:12)
    at ApiBuilder.self.proxyRouter (/var/task/node_modules/claudia-api-builder/src/api-builder.js:322:19)

Maybe you can catch the error from JSON.parse and use empty JSON in turn?

**Comment by gojko** [comment]
no, that breaks backwards compatibility. sending application/json with invalid json should throw an error. If you need to send invalid JSON, then use text/plain or something else as the content type.

**Comment by legetz** [comment]
I understand that but it will crash the whole Lambda and returns 502 error:
2017-03-16T11:59:20.556Z	f97a5269-0a3f-11e7-b93a-6d9d98ea6f88	SyntaxError: Unexpected end of input
    at Object.parse (native)
    at convertApiGWProxyRequest (/var/task/node_modules/claudia-api-builder/src/convert-api-gw-proxy-request.js:80:22)
    at ApiBuilder.getRequest (/var/task/node_modules/claudia-api-builder/src/api-builder.js:233:12)
    at ApiBuilder.self.proxyRouter (/var/task/node_modules/claudia-api-builder/src/api-builder.js:322:19)
2017-03-16T11:59:20.637Z END RequestId: f97a5269-0a3f-11e7-b93a-6d9d98ea6f88
2017-03-16T11:59:20.637Z REPORT RequestId: f97a5269-0a3f-11e7-b93a-6d9d98ea6f88	Duration: 6335.45 ms	Billed Duration: 6400 ms 	Memory Size: 128 MB	Max Memory Used: 23 MB
2017-03-16T11:59:20.637Z RequestId: f97a5269-0a3f-11e7-b93a-6d9d98ea6f88 Process exited before completing request

Next API call will take around 10 seconds to complete since AWS needs to start another thread/instance to fullfill the valid request.

**Comment by gojko** [comment]
10 secs to start a new lambda is likely a problem with your aws account, and you should speak to your aws account manager about that. launching a new lambda with node.js should take < 1s.

having said that, if you want to submit a PR that responds with 400 bad request in case of a json parse error, that would be useful and I'll merge it. The change should probably go somewhere here: https://github.com/claudiajs/claudia-api-builder/blob/7f4ab2e3b29edd998688314a13dc4616b7a76785/src/api-builder.js#L322 and could use `packResult` to return a "successful" result with code 400 instead of processing

**Comment by gojko** [comment]
2.4.2 now on NPM handles such errors more gracefully, so it won't crash but report a 500 invalid request
